[package]
name = "rust"
version = "0.1.0"
authors = ["Lexkane <alexkane.vip@gmail.com>"]
edition = "2018"

[lib]
name = "rust"
crate-type = ["staticlib", "cdylib"]


[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
